[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[forms]
  [forms."contact-ghotsvip"]
    success_url = "/"
    spam_threshold = 0.8

[forms."contact-ghotsvip".fields]
  name = { type = "text", required = true }
  email = { type = "email", required = true }
  message = { type = "text", required = true }
  bot-field = { type = "text" }

[build.processing]
  skip_processing = false
